name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize Conda Environment
        uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python
      - name: Test
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pytest tests -s
