name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Initialize Conda Environment
        uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: conda install --yes --channel pytorch --file requirements.txt
      - run: pytest -s
